import Header from './components/Header'
import './globals.css'
import localFont from 'next/font/local'
 
const subjectivity = localFont({
  src: [
    {
      path: './font/Subjectivity-Thin.woff2',
      weight: '100',
      style: 'thin',
    },
    {
      path: './font/Subjectivity-Light.woff2',
      weight: '200',
      style: 'light',
    },
    {
      path: './font/Subjectivity-Regular.woff2',
      weight: '300',
      style: 'regular',
    },
    {
      path: './font/Subjectivity-Medium.woff2',
      weight: '400',
      style: 'medium',
    },
    {
      path: './font/Subjectivity-ExtraBold.woff2',
      weight: '700',
      style: 'extrabold',
    },
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={subjectivity.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
